In [ ]:
import pandas as pd


pd.set_option('display.max_columns', None)
df = pd.read_csv('/content/whoscored_player_stats_defensive.csv')
display(df.head())

,Player_ID,Team_Name,Player_Name,height,weight,age,isManOfTheMatch,isActive,playedPositions,playedPositionsShort,teamRegionName,regionCode,tournamentShortName,apps,subOn,tacklePerGame,interceptionPerGame,foulsPerGame,offsideWonPerGame,clearancePerGame,wasDribbledPerGame,outfielderBlockPerGame,name,firstName,lastName,playerId,positionText,teamId,teamName,seasonId,seasonName,isOpta,tournamentId,tournamentRegionId,tournamentRegionCode,tournamentRegionName,tournamentName,rating,minsPlayed,goalOwn,ranking
0,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),Italy,fr,ISA,29,1,1.965517,0.724138,1.206897,0.0,1.413793,0.655172,0.172414,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,80,AC Milan,10732,2025/2026,True,5,108,it,Italy,Serie A,7.054483,2551,0.0,1
1,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),France,fr,WCQ,3,2,1.333333,0.333333,0.666667,0.0,0.333333,0.333333,0.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,341,France,10555,2025/2026,True,721,247,cint,International,World Cup Qualification UEFA,6.903333,104,0.0,2
2,116609,France,Adrien Rabiot,191,86,31,False,False,-MC-ML-,M(CL),France,fr,FL1,1,0,0.000000,0.000000,2.000000,0.0,1.000000,0.000000,0.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,249,Marseille,10792,2025/2026,True,22,74,fr,France,Ligue 1,6.780000,90,0.0,3
3,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),Italy,fr,ICI,2,0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,80,AC Milan,10773,2025/2026,False,60,108,it,Italy,Coppa Italia,0.000000,0,0.0,4
4,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),Italy,fr,ISC,1,0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,80,AC Milan,10897,2024/2025,False,64,108,it,Italy,Supercoppa Italiana,0.000000,0,0.0,5

In [ ]:
columns_to_drop = [
    'height', 'weight', 'age', 'isManOfTheMatch', 'isActive',
    'playedPositions', 'playedPositionsShort', 'teamRegionName', 'regionCode',
    'tournamentShortName', 'subOn', 'name', 'firstName', 'lastName',
    'playerId', 'teamId', 'teamName', 'seasonId', 'seasonName', 'isOpta',
    'tournamentId', 'tournamentRegionId', 'tournamentRegionCode',
    'tournamentRegionName', 'tournamentName', 'rating', 'minsPlayed', 'ranking'
]

df_dropped = df.drop(columns=columns_to_drop)

# Display the first 5 rows of the DataFrame with the dropped columns
display(df_dropped.head())

,Player_ID,Team_Name,Player_Name,apps,tacklePerGame,interceptionPerGame,foulsPerGame,offsideWonPerGame,clearancePerGame,wasDribbledPerGame,outfielderBlockPerGame,positionText,goalOwn
0,116609,France,Adrien Rabiot,29,1.965517,0.724138,1.206897,0.0,1.413793,0.655172,0.172414,Midfielder,0.0
1,116609,France,Adrien Rabiot,3,1.333333,0.333333,0.666667,0.0,0.333333,0.333333,0.000000,Midfielder,0.0
2,116609,France,Adrien Rabiot,1,0.000000,0.000000,2.000000,0.0,1.000000,0.000000,0.000000,Midfielder,0.0
3,116609,France,Adrien Rabiot,2,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,Midfielder,0.0
4,116609,France,Adrien Rabiot,1,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,Midfielder,0.0

In [ ]:
aggregation_functions = {
    'apps': 'sum',
    'goalOwn': 'sum',
    'tacklePerGame': lambda x: x[x != 0].mean(),
    'interceptionPerGame': lambda x: x[x != 0].mean(),
    'foulsPerGame': lambda x: x[x != 0].mean(),
    'offsideWonPerGame': lambda x: x[x != 0].mean(),
    'clearancePerGame': lambda x: x[x != 0].mean(),
    'wasDribbledPerGame': lambda x: x[x != 0].mean(),
    'outfielderBlockPerGame': lambda x: x[x != 0].mean()
}

df_aggregated = df.groupby(['Player_ID', 'Player_Name']).agg(aggregation_functions).reset_index()
display(df_aggregated.head())

,Player_ID,Player_Name,apps,goalOwn,tacklePerGame,interceptionPerGame,foulsPerGame,offsideWonPerGame,clearancePerGame,wasDribbledPerGame,outfielderBlockPerGame
0,5583,Cristiano Ronaldo,38,0.0,NaN,NaN,0.600000,NaN,NaN,NaN,NaN
1,8280,Craig Gordon,8,0.0,NaN,NaN,NaN,NaN,1.055556,NaN,NaN
2,11119,Lionel Messi,41,0.0,0.946429,0.142857,0.435714,NaN,0.250000,1.059524,0.250000
3,13754,Manuel Neuer,43,0.0,NaN,NaN,NaN,NaN,0.863636,0.090909,NaN
4,20874,Luka Modric,55,0.0,0.736111,0.687908,0.421569,0.058824,0.698529,0.437092,0.238971

In [ ]:
df_aggregated.to_csv('aggregated_player_stats.csv', index=False)